import type { Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";

/** Monaco 테마 식별자 - next-themes와 동일한 키를 사용 */
export const CUSTOM_THEME_KEYS = [
  "dracula",
  "nord",
  "monokai",
  "solarized-dark",
  "github-dark",
] as const;

export type CustomThemeKey = (typeof CUSTOM_THEME_KEYS)[number];

/** cheolsu-light: 프로젝트의 기본 라이트 테마 */
export const LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "0d0d0d", background: "ffffff" },
    { token: "keyword", foreground: "0d0d0d", fontStyle: "bold" },
    { token: "keyword.control", foreground: "e74322", fontStyle: "bold" },
    { token: "keyword.json", foreground: "e74322" },
    { token: "string", foreground: "5aab9f" },
    { token: "string.key.json", foreground: "0d0d0d", fontStyle: "bold" },
    { token: "string.value.json", foreground: "5aab9f" },
    { token: "string.escape", foreground: "d97706" },
    { token: "number", foreground: "d97706" },
    { token: "comment", foreground: "6b7280", fontStyle: "italic" },
    { token: "type", foreground: "475569" },
    { token: "type.identifier", foreground: "475569" },
    { token: "operator", foreground: "00bcd5", fontStyle: "bold" },
    { token: "delimiter", foreground: "94a3b8" },
    { token: "delimiter.bracket", foreground: "64748b" },
    { token: "identifier", foreground: "0d0d0d" },
    { token: "variable", foreground: "00bcd5" },
    { token: "variable.parameter", foreground: "475569" },
    { token: "tag", foreground: "e74322" },
    { token: "attribute.name", foreground: "00bcd5" },
    { token: "attribute.value", foreground: "5aab9f" },
    { token: "regexp", foreground: "d97706" },
    { token: "annotation", foreground: "e74322" },
    { token: "metatag", foreground: "94a3b8" },
  ],
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#0d0d0d",
    "editor.lineHighlightBackground": "#f8fafc",
    "editor.selectionBackground": "#bae6fd80",
    "editor.selectionHighlightBackground": "#e0f2fe",
    "editor.findMatchBackground": "#fde68a80",
    "editor.findMatchHighlightBackground": "#fef3c7",
    "editorLineNumber.foreground": "#94a3b8",
    "editorLineNumber.activeForeground": "#0d0d0d",
    "editorCursor.foreground": "#00bcd5",
    "editorIndentGuide.background": "#f1f5f9",
    "editorIndentGuide.activeBackground": "#e2e8f0",

    "editorWidget.background": "#ffffff",
    "editorWidget.border": "#e5e7eb",
    "editorWidget.foreground": "#0d0d0d",

    "editorSuggestWidget.background": "#ffffff",
    "editorSuggestWidget.border": "#e5e7eb",
    "editorSuggestWidget.foreground": "#0d0d0d",
    "editorSuggestWidget.selectedBackground": "#e0f2fe",
    "editorSuggestWidget.selectedForeground": "#0c4a6e",
    "editorSuggestWidget.highlightForeground": "#0ea5e9",
    "editorSuggestWidget.focusHighlightForeground": "#0284c7",

    "list.hoverBackground": "#f1f5f9",
    "list.hoverForeground": "#0d0d0d",
    "list.activeSelectionBackground": "#e0f2fe",
    "list.activeSelectionForeground": "#0c4a6e",
    "list.inactiveSelectionBackground": "#f1f5f9",
    "list.inactiveSelectionForeground": "#0d0d0d",
    "list.focusBackground": "#e0f2fe",
    "list.focusForeground": "#0c4a6e",

    "scrollbarSlider.background": "#cbd5e180",
    "scrollbarSlider.hoverBackground": "#94a3b8",
    "scrollbarSlider.activeBackground": "#64748b",
  },
};

/** cheolsu-dark: 프로젝트의 기본 다크 테마 */
export const DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "b4b4b9", background: "0a0a0a" },
    { token: "keyword", foreground: "45cbda", fontStyle: "bold" },
    { token: "keyword.control", foreground: "f87171", fontStyle: "bold" },
    { token: "keyword.json", foreground: "f87171" },
    { token: "string", foreground: "5aab9f" },
    { token: "string.key.json", foreground: "45cbda" },
    { token: "string.value.json", foreground: "5aab9f" },
    { token: "string.escape", foreground: "d97706" },
    { token: "number", foreground: "d97706" },
    { token: "comment", foreground: "a1a1aa", fontStyle: "italic" },
    { token: "type", foreground: "5aab9f" },
    { token: "type.identifier", foreground: "5aab9f" },
    { token: "operator", foreground: "45cbda", fontStyle: "bold" },
    { token: "delimiter", foreground: "64748b" },
    { token: "delimiter.bracket", foreground: "71717a" },
    { token: "identifier", foreground: "b4b4b9" },
    { token: "variable", foreground: "45cbda" },
    { token: "variable.parameter", foreground: "a1a1aa" },
    { token: "tag", foreground: "f87171" },
    { token: "attribute.name", foreground: "45cbda" },
    { token: "attribute.value", foreground: "5aab9f" },
    { token: "regexp", foreground: "d97706" },
    { token: "annotation", foreground: "f87171" },
    { token: "metatag", foreground: "64748b" },
  ],
  colors: {
    "editor.background": "#0a0a0a",
    "editor.foreground": "#b4b4b9",
    "editor.lineHighlightBackground": "#141414",
    "editor.selectionBackground": "#0e749060",
    "editor.selectionHighlightBackground": "#0e749030",
    "editor.findMatchBackground": "#0e749080",
    "editor.findMatchHighlightBackground": "#45cbda30",
    "editor.findMatchBorder": "#0e7490",
    "editor.findMatchHighlightBorder": "#45cbda50",
    "editorLineNumber.foreground": "#3f3f46",
    "editorLineNumber.activeForeground": "#a1a1aa",
    "editorCursor.foreground": "#45cbda",
    "editorIndentGuide.background": "#1c1c1c",
    "editorIndentGuide.activeBackground": "#262626",

    "editorWidget.background": "#141414",
    "editorWidget.border": "#262626",
    "editorWidget.foreground": "#b4b4b9",

    "editorSuggestWidget.background": "#141414",
    "editorSuggestWidget.border": "#262626",
    "editorSuggestWidget.foreground": "#b4b4b9",
    "editorSuggestWidget.selectedBackground": "#0e7490",
    "editorSuggestWidget.selectedForeground": "#b4b4b9",
    "editorSuggestWidget.highlightForeground": "#22d3ee",
    "editorSuggestWidget.focusHighlightForeground": "#06b6d4",

    "editorFindWidget.background": "#141414",
    "editorFindWidget.border": "#262626",
    "editorFindWidget.foreground": "#b4b4b9",

    "list.hoverBackground": "#1c1c1c",
    "list.hoverForeground": "#b4b4b9",
    "list.activeSelectionBackground": "#0e7490",
    "list.activeSelectionForeground": "#b4b4b9",
    "list.inactiveSelectionBackground": "#1c1c1c",
    "list.inactiveSelectionForeground": "#d4d4d8",
    "list.focusBackground": "#0e7490",
    "list.focusForeground": "#b4b4b9",

    "scrollbarSlider.background": "#26262680",
    "scrollbarSlider.hoverBackground": "#3f3f46",
    "scrollbarSlider.activeBackground": "#52525b",
  },
};

/** cheolsu-dracula: Dracula 공식 팔레트 기반 */
export const DRACULA_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2", background: "282a36" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "keyword.control", foreground: "ff79c6", fontStyle: "bold" },
    { token: "keyword.json", foreground: "bd93f9" },
    { token: "string", foreground: "f1fa8c" },
    { token: "string.key.json", foreground: "8be9fd" },
    { token: "string.value.json", foreground: "f1fa8c" },
    { token: "string.escape", foreground: "ff79c6" },
    { token: "number", foreground: "bd93f9" },
    { token: "comment", foreground: "6272a4", fontStyle: "italic" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "type.identifier", foreground: "8be9fd", fontStyle: "italic" },
    { token: "operator", foreground: "ff79c6" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "delimiter.bracket", foreground: "f8f8f2" },
    { token: "identifier", foreground: "f8f8f2" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "variable.parameter", foreground: "ffb86c", fontStyle: "italic" },
    { token: "tag", foreground: "ff79c6" },
    { token: "attribute.name", foreground: "50fa7b" },
    { token: "attribute.value", foreground: "f1fa8c" },
    { token: "regexp", foreground: "f1fa8c" },
    { token: "annotation", foreground: "50fa7b" },
    { token: "metatag", foreground: "ff79c6" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#44475a40",
    "editor.selectionBackground": "#44475a",
    "editor.selectionHighlightBackground": "#424450",
    "editor.findMatchBackground": "#ffb86c80",
    "editor.findMatchHighlightBackground": "#50fa7b40",
    "editorLineNumber.foreground": "#6272a4",
    "editorLineNumber.activeForeground": "#f8f8f2",
    "editorCursor.foreground": "#f8f8f2",
    "editorIndentGuide.background": "#44475a",
    "editorIndentGuide.activeBackground": "#6272a4",

    "editorWidget.background": "#21222c",
    "editorWidget.border": "#44475a",
    "editorWidget.foreground": "#f8f8f2",

    "editorSuggestWidget.background": "#21222c",
    "editorSuggestWidget.border": "#44475a",
    "editorSuggestWidget.foreground": "#f8f8f2",
    "editorSuggestWidget.selectedBackground": "#44475a",
    "editorSuggestWidget.selectedForeground": "#f8f8f2",
    "editorSuggestWidget.highlightForeground": "#8be9fd",
    "editorSuggestWidget.focusHighlightForeground": "#50fa7b",

    "editorFindWidget.background": "#21222c",
    "editorFindWidget.border": "#44475a",
    "editorFindWidget.foreground": "#f8f8f2",

    "list.hoverBackground": "#44475a",
    "list.hoverForeground": "#f8f8f2",
    "list.activeSelectionBackground": "#44475a",
    "list.activeSelectionForeground": "#f8f8f2",
    "list.inactiveSelectionBackground": "#343746",
    "list.inactiveSelectionForeground": "#f8f8f2",
    "list.focusBackground": "#44475a",
    "list.focusForeground": "#f8f8f2",

    "scrollbarSlider.background": "#44475a80",
    "scrollbarSlider.hoverBackground": "#6272a4",
    "scrollbarSlider.activeBackground": "#6272a4",
  },
};

/** cheolsu-nord: Nord 공식 팔레트 기반 */
export const NORD_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "d8dee9", background: "2e3440" },
    { token: "keyword", foreground: "81a1c1" },
    { token: "keyword.control", foreground: "b48ead", fontStyle: "bold" },
    { token: "keyword.json", foreground: "b48ead" },
    { token: "string", foreground: "a3be8c" },
    { token: "string.key.json", foreground: "8fbcbb" },
    { token: "string.value.json", foreground: "a3be8c" },
    { token: "string.escape", foreground: "ebcb8b" },
    { token: "number", foreground: "b48ead" },
    { token: "comment", foreground: "616e88", fontStyle: "italic" },
    { token: "type", foreground: "8fbcbb" },
    { token: "type.identifier", foreground: "8fbcbb" },
    { token: "operator", foreground: "81a1c1" },
    { token: "delimiter", foreground: "eceff4" },
    { token: "delimiter.bracket", foreground: "eceff4" },
    { token: "identifier", foreground: "d8dee9" },
    { token: "variable", foreground: "d8dee9" },
    { token: "variable.parameter", foreground: "d8dee9" },
    { token: "tag", foreground: "81a1c1" },
    { token: "attribute.name", foreground: "8fbcbb" },
    { token: "attribute.value", foreground: "a3be8c" },
    { token: "regexp", foreground: "ebcb8b" },
    { token: "annotation", foreground: "88c0d0" },
    { token: "metatag", foreground: "81a1c1" },
  ],
  colors: {
    "editor.background": "#2e3440",
    "editor.foreground": "#d8dee9",
    "editor.lineHighlightBackground": "#3b425280",
    "editor.selectionBackground": "#434c5e",
    "editor.selectionHighlightBackground": "#434c5e80",
    "editor.findMatchBackground": "#ebcb8b80",
    "editor.findMatchHighlightBackground": "#88c0d040",
    "editorLineNumber.foreground": "#4c566a",
    "editorLineNumber.activeForeground": "#d8dee9",
    "editorCursor.foreground": "#d8dee9",
    "editorIndentGuide.background": "#434c5e",
    "editorIndentGuide.activeBackground": "#4c566a",

    "editorWidget.background": "#3b4252",
    "editorWidget.border": "#4c566a",
    "editorWidget.foreground": "#d8dee9",

    "editorSuggestWidget.background": "#3b4252",
    "editorSuggestWidget.border": "#4c566a",
    "editorSuggestWidget.foreground": "#d8dee9",
    "editorSuggestWidget.selectedBackground": "#434c5e",
    "editorSuggestWidget.selectedForeground": "#eceff4",
    "editorSuggestWidget.highlightForeground": "#88c0d0",
    "editorSuggestWidget.focusHighlightForeground": "#8fbcbb",

    "editorFindWidget.background": "#3b4252",
    "editorFindWidget.border": "#4c566a",
    "editorFindWidget.foreground": "#d8dee9",

    "list.hoverBackground": "#434c5e",
    "list.hoverForeground": "#eceff4",
    "list.activeSelectionBackground": "#4c566a",
    "list.activeSelectionForeground": "#eceff4",
    "list.inactiveSelectionBackground": "#3b4252",
    "list.inactiveSelectionForeground": "#d8dee9",
    "list.focusBackground": "#434c5e",
    "list.focusForeground": "#eceff4",

    "scrollbarSlider.background": "#4c566a80",
    "scrollbarSlider.hoverBackground": "#4c566a",
    "scrollbarSlider.activeBackground": "#616e88",
  },
};

/** cheolsu-monokai: Monokai 공식 팔레트 기반 */
export const MONOKAI_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2", background: "272822" },
    { token: "keyword", foreground: "f92672" },
    { token: "keyword.control", foreground: "f92672", fontStyle: "bold" },
    { token: "keyword.json", foreground: "ae81ff" },
    { token: "string", foreground: "e6db74" },
    { token: "string.key.json", foreground: "f8f8f2" },
    { token: "string.value.json", foreground: "e6db74" },
    { token: "string.escape", foreground: "ae81ff" },
    { token: "number", foreground: "ae81ff" },
    { token: "comment", foreground: "75715e", fontStyle: "italic" },
    { token: "type", foreground: "66d9ef", fontStyle: "italic" },
    { token: "type.identifier", foreground: "66d9ef", fontStyle: "italic" },
    { token: "operator", foreground: "f92672" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "delimiter.bracket", foreground: "f8f8f2" },
    { token: "identifier", foreground: "f8f8f2" },
    { token: "variable", foreground: "fd971f" },
    { token: "variable.parameter", foreground: "fd971f", fontStyle: "italic" },
    { token: "tag", foreground: "f92672" },
    { token: "attribute.name", foreground: "a6e22e" },
    { token: "attribute.value", foreground: "e6db74" },
    { token: "regexp", foreground: "e6db74" },
    { token: "annotation", foreground: "a6e22e" },
    { token: "metatag", foreground: "f92672" },
  ],
  colors: {
    "editor.background": "#272822",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#3e3d32",
    "editor.selectionBackground": "#49483e",
    "editor.selectionHighlightBackground": "#49483e80",
    "editor.findMatchBackground": "#fd971f80",
    "editor.findMatchHighlightBackground": "#a6e22e40",
    "editorLineNumber.foreground": "#75715e",
    "editorLineNumber.activeForeground": "#f8f8f2",
    "editorCursor.foreground": "#f8f8f0",
    "editorIndentGuide.background": "#3e3d32",
    "editorIndentGuide.activeBackground": "#75715e",

    "editorWidget.background": "#1e1f1c",
    "editorWidget.border": "#3e3d32",
    "editorWidget.foreground": "#f8f8f2",

    "editorSuggestWidget.background": "#1e1f1c",
    "editorSuggestWidget.border": "#3e3d32",
    "editorSuggestWidget.foreground": "#f8f8f2",
    "editorSuggestWidget.selectedBackground": "#49483e",
    "editorSuggestWidget.selectedForeground": "#f8f8f2",
    "editorSuggestWidget.highlightForeground": "#66d9ef",
    "editorSuggestWidget.focusHighlightForeground": "#a6e22e",

    "editorFindWidget.background": "#1e1f1c",
    "editorFindWidget.border": "#3e3d32",
    "editorFindWidget.foreground": "#f8f8f2",

    "list.hoverBackground": "#3e3d32",
    "list.hoverForeground": "#f8f8f2",
    "list.activeSelectionBackground": "#49483e",
    "list.activeSelectionForeground": "#f8f8f2",
    "list.inactiveSelectionBackground": "#3e3d32",
    "list.inactiveSelectionForeground": "#f8f8f2",
    "list.focusBackground": "#49483e",
    "list.focusForeground": "#f8f8f2",

    "scrollbarSlider.background": "#49483e80",
    "scrollbarSlider.hoverBackground": "#75715e",
    "scrollbarSlider.activeBackground": "#75715e",
  },
};

/** cheolsu-solarized-dark: Solarized Dark 공식 팔레트 기반 */
export const SOLARIZED_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "839496", background: "002b36" },
    { token: "keyword", foreground: "859900" },
    { token: "keyword.control", foreground: "cb4b16", fontStyle: "bold" },
    { token: "keyword.json", foreground: "d33682" },
    { token: "string", foreground: "2aa198" },
    { token: "string.key.json", foreground: "268bd2" },
    { token: "string.value.json", foreground: "2aa198" },
    { token: "string.escape", foreground: "cb4b16" },
    { token: "number", foreground: "d33682" },
    { token: "comment", foreground: "586e75", fontStyle: "italic" },
    { token: "type", foreground: "b58900" },
    { token: "type.identifier", foreground: "b58900" },
    { token: "operator", foreground: "cb4b16" },
    { token: "delimiter", foreground: "93a1a1" },
    { token: "delimiter.bracket", foreground: "93a1a1" },
    { token: "identifier", foreground: "839496" },
    { token: "variable", foreground: "268bd2" },
    { token: "variable.parameter", foreground: "839496" },
    { token: "tag", foreground: "268bd2" },
    { token: "attribute.name", foreground: "93a1a1" },
    { token: "attribute.value", foreground: "2aa198" },
    { token: "regexp", foreground: "dc322f" },
    { token: "annotation", foreground: "268bd2" },
    { token: "metatag", foreground: "859900" },
  ],
  colors: {
    "editor.background": "#002b36",
    "editor.foreground": "#839496",
    "editor.lineHighlightBackground": "#073642",
    "editor.selectionBackground": "#274642",
    "editor.selectionHighlightBackground": "#004052",
    "editor.findMatchBackground": "#b5890080",
    "editor.findMatchHighlightBackground": "#268bd240",
    "editorLineNumber.foreground": "#586e75",
    "editorLineNumber.activeForeground": "#93a1a1",
    "editorCursor.foreground": "#93a1a1",
    "editorIndentGuide.background": "#073642",
    "editorIndentGuide.activeBackground": "#586e75",

    "editorWidget.background": "#073642",
    "editorWidget.border": "#073642",
    "editorWidget.foreground": "#839496",

    "editorSuggestWidget.background": "#073642",
    "editorSuggestWidget.border": "#073642",
    "editorSuggestWidget.foreground": "#839496",
    "editorSuggestWidget.selectedBackground": "#004052",
    "editorSuggestWidget.selectedForeground": "#fdf6e3",
    "editorSuggestWidget.highlightForeground": "#268bd2",
    "editorSuggestWidget.focusHighlightForeground": "#b58900",

    "editorFindWidget.background": "#073642",
    "editorFindWidget.border": "#073642",
    "editorFindWidget.foreground": "#839496",

    "list.hoverBackground": "#073642",
    "list.hoverForeground": "#fdf6e3",
    "list.activeSelectionBackground": "#004052",
    "list.activeSelectionForeground": "#fdf6e3",
    "list.inactiveSelectionBackground": "#073642",
    "list.inactiveSelectionForeground": "#839496",
    "list.focusBackground": "#004052",
    "list.focusForeground": "#fdf6e3",

    "scrollbarSlider.background": "#07364280",
    "scrollbarSlider.hoverBackground": "#586e75",
    "scrollbarSlider.activeBackground": "#586e75",
  },
};

/** cheolsu-github-dark: GitHub Dark (Primer) 공식 팔레트 기반 */
export const GITHUB_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "c9d1d9", background: "0d1117" },
    { token: "keyword", foreground: "ff7b72" },
    { token: "keyword.control", foreground: "ff7b72", fontStyle: "bold" },
    { token: "keyword.json", foreground: "79c0ff" },
    { token: "string", foreground: "a5d6ff" },
    { token: "string.key.json", foreground: "79c0ff" },
    { token: "string.value.json", foreground: "a5d6ff" },
    { token: "string.escape", foreground: "79c0ff" },
    { token: "number", foreground: "79c0ff" },
    { token: "comment", foreground: "8b949e", fontStyle: "italic" },
    { token: "type", foreground: "ffa657" },
    { token: "type.identifier", foreground: "ffa657" },
    { token: "operator", foreground: "ff7b72" },
    { token: "delimiter", foreground: "c9d1d9" },
    { token: "delimiter.bracket", foreground: "c9d1d9" },
    { token: "identifier", foreground: "c9d1d9" },
    { token: "variable", foreground: "d2a8ff" },
    { token: "variable.parameter", foreground: "ffa657" },
    { token: "tag", foreground: "7ee787" },
    { token: "attribute.name", foreground: "79c0ff" },
    { token: "attribute.value", foreground: "a5d6ff" },
    { token: "regexp", foreground: "7ee787" },
    { token: "annotation", foreground: "79c0ff" },
    { token: "metatag", foreground: "ff7b72" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "editor.lineHighlightBackground": "#161b22",
    "editor.selectionBackground": "#1f6feb66",
    "editor.selectionHighlightBackground": "#388bfd26",
    "editor.findMatchBackground": "#ffa65766",
    "editor.findMatchHighlightBackground": "#58a6ff33",
    "editorLineNumber.foreground": "#484f58",
    "editorLineNumber.activeForeground": "#c9d1d9",
    "editorCursor.foreground": "#58a6ff",
    "editorIndentGuide.background": "#21262d",
    "editorIndentGuide.activeBackground": "#30363d",

    "editorWidget.background": "#161b22",
    "editorWidget.border": "#30363d",
    "editorWidget.foreground": "#c9d1d9",

    "editorSuggestWidget.background": "#161b22",
    "editorSuggestWidget.border": "#30363d",
    "editorSuggestWidget.foreground": "#c9d1d9",
    "editorSuggestWidget.selectedBackground": "#1f6feb",
    "editorSuggestWidget.selectedForeground": "#ffffff",
    "editorSuggestWidget.highlightForeground": "#58a6ff",
    "editorSuggestWidget.focusHighlightForeground": "#79c0ff",

    "editorFindWidget.background": "#161b22",
    "editorFindWidget.border": "#30363d",
    "editorFindWidget.foreground": "#c9d1d9",

    "list.hoverBackground": "#161b22",
    "list.hoverForeground": "#c9d1d9",
    "list.activeSelectionBackground": "#1f6feb",
    "list.activeSelectionForeground": "#ffffff",
    "list.inactiveSelectionBackground": "#161b22",
    "list.inactiveSelectionForeground": "#c9d1d9",
    "list.focusBackground": "#1f6feb",
    "list.focusForeground": "#ffffff",

    "scrollbarSlider.background": "#30363d80",
    "scrollbarSlider.hoverBackground": "#484f58",
    "scrollbarSlider.activeBackground": "#6e7681",
  },
};

/** resolvedTheme → Monaco 테마 이름 변환 */
export function getMonacoThemeName(resolvedTheme: string | undefined): string {
  if (!resolvedTheme || resolvedTheme === "light") return "cheolsu-light";
  if (resolvedTheme === "dark") return "cheolsu-dark";
  return `cheolsu-${resolvedTheme}`;
}

const THEMES_BY_KEY: Record<string, editor.IStandaloneThemeData> = {
  "cheolsu-light": LIGHT_THEME,
  "cheolsu-dark": DARK_THEME,
  "cheolsu-dracula": DRACULA_THEME,
  "cheolsu-nord": NORD_THEME,
  "cheolsu-monokai": MONOKAI_THEME,
  "cheolsu-solarized-dark": SOLARIZED_DARK_THEME,
  "cheolsu-github-dark": GITHUB_DARK_THEME,
};

let isThemesRegistered = false;

/** 모든 cheolsu-* Monaco 테마를 한 번만 등록 */
export function setupMonacoThemes(monaco: Monaco): void {
  if (isThemesRegistered) return;

  for (const [name, data] of Object.entries(THEMES_BY_KEY)) {
    monaco.editor.defineTheme(name, data);
  }

  isThemesRegistered = true;
}
