[workspace]
resolver = "2"

members = [
  "crates/proxyapi_v2",
  "crates/proxy_v2_models",
  "crates/proxy_daemon",
  "crates/cheolsu_ops",
  "crates/mcp_server",
  "crates/tui",
  "desktop/src-tauri",
  "crates/scripting",
]

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
opt-level = "s"
