[package]
name = "proxy_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
proxy_v2_models = { path = "../proxy_v2_models" }
proxyapi_v2 = { path = "../proxyapi_v2", features = [
  "decoder",
  "http2",
  "rcgen-ca",
  "openssl-ca",
  "native-tls-client",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
hyper-util = "0.1"
hyper-rustls = "0.27"
tokio-rustls = "0.26"
bytes = "1.0"
futures-util = "0.3"
http-body-util = "0.1"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.1.2"
tokio-stream = "0.1.17"
regex = "1.0"
dirs = "6.0"
nix = { version = "0.29", features = ["signal", "process"] }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
