[package]
name = "proxy_daemon"
version = "0.1.1"
edition = "2021"

[dependencies]
proxy_v2_models = { path = "../proxy_v2_models" }
proxyapi_v2 = { path = "../proxyapi_v2", features = [
  "decoder",
  "http2",
  "rcgen-ca",
  "openssl-ca",
  "native-tls-client",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
hyper-util = "0.1"
hyper-rustls = "0.27"
tokio-rustls = "0.26"
bytes = "1.0"
futures-util = "0.3"
http-body-util = "0.1"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.1.2"
tokio-stream = "0.1.17"
regex = "1.0"
lru = "0.16"
base64 = "0.22"
dirs = "6.0"
nix = { version = "0.31", features = ["signal", "process"] }
tokio-tungstenite = "0.28.0"
thiserror = "2"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
scripting = { path = "../scripting" }
notify = { version = "8", default-features = false, features = ["macos_kqueue"] }
parking_lot = "0.12"
similar = "2"
rustls-pemfile = "2.0.0"
x509-parser = "0.18.1"
sha2 = "0.10"
openssl = "0.10.76"
protox = "0.9"
prost-reflect = { version = "0.16", features = ["serde"] }
async-stream = "0.3"
serde_yml = "0.0.12"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3"
rcgen = "0.14"
http = "1"
