name: Rust Format Check

on:
  push:
    branches: [ master ]
    paths:
      - 'tauri-ui/src-tauri/**'
      - 'proxyapi/**'
      - 'proxyapi_models/**'
      - '.github/workflows/rust-lint.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'tauri-ui/src-tauri/**'
      - 'proxyapi/**'
      - 'proxyapi_models/**'
      - '.github/workflows/rust-lint.yml'

jobs:
  rust-format:
    name: Rust Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        cache: true
        matcher: true

    - name: Check Rust formatting
      run: |
        echo "Checking Rust code formatting..."
        cargo fmt --all -- --check
